version: "3.7"

services:
  sayit_db:
    image: "postgres:13"
    container_name: sayit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    networks:
      - sayit_net

volumes:
  postgres_data:

networks:
  sayit_net: