version: "3.7"

services:
  sayit_db:
    image: "postgres:13"
    container_name: sayit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    networks:
      - sayit_net

  redis:
    container_name: sayit_redis
    image: "redis:latest"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sayit_net

volumes:
  postgres_data:
  redis_data:

networks:
  sayit_net: