default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sayit_development

test:
  <<: *default
  database: sayit_test

production:
  <<: *default
  database: sayit_production
  username: sayit
  password: <%= ENV["SAYIT_DATABASE_PASSWORD"] %>
